name: Pack workflow

on:
    workflow_run:
        workflows: [ "Build" ]
        types: [ requested ]
        branches: [ master ]

    workflow_dispatch:
        inputs:
            version:
                description: 'Version'
                required: true

env:
    BUILD_CONFIG: 'Release'

jobs:
  pack:
      runs-on: ubuntu-latest
      steps:
      - name: Determine version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            echo "VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
          fi
          echo "$GITHUB_ENV"

      - name: 'Validate SemVer'
        run: |
          if [[ ! "$VERSION" =~ ^([0-9]+\.){2}[0-9]+$ ]]; then
            echo "The version does not match the SemVer format (X.Y.Z). Please provide a valid version."
            exit 1
          fi

      - name: 'Print version'
        run: |
          echo "$VERSION"

      - name: Checkout
        uses: actions/checkout@v4
        with:
            lfs: true
            fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Pack
        run: |
          dotnet pack \
          --output ./artifacts \
          --configuration $BUILD_CONFIG \
          --version-suffix ${{ env.VERSION }}

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ./artifacts
